options:
  workerPool: anz-cx-cloudbuild-np-9333ec/custom-workers-pool-poc
steps:
  - name: gcr.io/cloud-builders/docker
    id: 'build-image with docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/google-containers/cassandra@sha256:a1730e0ef7c05ad0b416089f957ffa6055d08340acd09056df7ca9bf820b40a7
  - name: gcr.io/cloud-builders/gcloud
    id: 'test cloud sql connectivity'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud --verbosity=debug sql instances list
  - name: gcr.io/cloud-builders/gcloud
    id: 'test cloudbuild api connectivity'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud --verbosity=debug builds list