options:
  workerPool: anz-cx-cloudbuild-dev-5ef683/custom-workers-dev-pool
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/anz-cs-splunk-np-0c623e/hello-world', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/anz-cs-splunk-np-0c623e/hello-world']
logsBucket: 'gs://anz-cs-splunk-np-0c623e_cloudbuild'